version: '3'
services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./back-end:/var/www/html
    depends_on:
      - database
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: innoscripta-saad
      MYSQL_USER: saadmaxell
      MYSQL_PASSWORD: noreply6SAAD
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./client:/app
